export const History = { 
 Games : [
  {
    Player1: "G",
    Player2: "M",
    Result: "NO",
    LocalEscudo: "/images/Porto.jpg",
    LocalNombre: "PORTO",
    LocalResultado: 1,
    VisitanteEscudo: "/images/BayernMunchen.png",
    VisitanteNombre: "BAYERN MUNICH",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "F",
    Result: "NO",
    LocalEscudo: "/images/Newcastle.png",
    LocalNombre: "NEWCASTLE",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Valencia.jpg",
    VisitanteNombre: "VALENCIA",
    VisitanteResultado: 1,
  },
  {
    Player1: "M",
    Player2: "F",
    Result: "L",
    LocalEscudo: "/images/Tottenham.png",
    LocalNombre: "TOTTENHAM",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Arsenal.jpg",
    VisitanteNombre: "ARSENAL",
    VisitanteResultado: 0,
  },
  {
    Player1: "M",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/RealMadrid.png",
    LocalNombre: "REAL MADRID",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Tottenham.png",
    VisitanteNombre: "TOTTENHAM",
    VisitanteResultado: 0,
  },
  {
    Player1: "M",
    Player2: "F",
    Result: "L",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Barcelona.webp",
    VisitanteNombre: "BARCELONA",
    VisitanteResultado: 2,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/Porto.jpg",
    LocalNombre: "PORTO",
    LocalResultado: 0,
    VisitanteEscudo: "/images/ManchesterCity.png",
    VisitanteNombre: "MANCHESTER CITY",
    VisitanteResultado: 1,
  },
  {
    Player1: "M",
    Player2: "F",
    Result: "L",
    LocalEscudo: "/images/ManchesterUnited.png",
    LocalNombre: "MANCHESTER UNITED",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Liverpool.png",
    VisitanteNombre: "LIVERPOOL",
    VisitanteResultado: 0,
  },

  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Ajax.png",
    LocalNombre: "AJAX",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Arsenal.jpg",
    VisitanteNombre: "ARSENAL",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/ManchesterUnited.png",
    LocalNombre: "MANCHESTER UNITED",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Juventus.jpg",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Newcastle.png",
    LocalNombre: "NEWCASTLE",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Zenit.png",
    VisitanteNombre: "ZENIT",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Liverpool.png",
    LocalNombre: "LIVERPOOL",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Tottenham.png",
    VisitanteNombre: "TOTTENHAM",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "NO",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PARIS SAINT GERMAIN",
    LocalResultado: 0,
    VisitanteEscudo: "/images/VillaReal.webp",
    VisitanteNombre: "VILLA REAL",
    VisitanteResultado: 1,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/BayernMunchen.png",
    LocalNombre: "BAYERN MUNICH",
    LocalResultado: 2,
    VisitanteEscudo: "/images/RealMadrid.png",
    VisitanteNombre: "REAL MADRID",
    VisitanteResultado: 2,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/BayernMunchen.png",
    LocalNombre: "BAYERN MUNICH",
    LocalResultado: 1,
    VisitanteEscudo: "/images/RealMadrid.png",
    VisitanteNombre: "REAL MADRID",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "F",
    Result: "L",
    LocalEscudo: "/images/Milan.png",
    LocalNombre: "MILAN",
    LocalResultado: 2,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PARIS SAINT GERMAIN",
    VisitanteResultado: 4,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/Liverpool.png",
    LocalNombre: "LIVERPOOL",
    LocalResultado: 1,
    VisitanteEscudo: "/images/Juventus.jpg",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 2,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PARIS SAINT GERMAIN",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Juventus.jpg",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Arsenal.jpg",
    LocalNombre: "ARSENAL",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Internazionale.png",
    VisitanteNombre: "INTER",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Barcelona.webp",
    LocalNombre: "BARCELONA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Milan.png",
    VisitanteNombre: "MILAN",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "NO",
    LocalEscudo: "/images/Porto.jpg",
    LocalNombre: "PORTO",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Liverpool.png",
    VisitanteNombre: "LIVERPOOL",
    VisitanteResultado: 1,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "NO",
    LocalEscudo: "/images/Internazionale.png",
    LocalNombre: "INTER",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Ajax.png",
    VisitanteNombre: "AJAX",
    VisitanteResultado: 1,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Arsenal.jpg",
    LocalNombre: "ARSENAL",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Valencia.jpg",
    VisitanteNombre: "VALENCIA",
    VisitanteResultado: 1,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/Sevilla.webp",
    LocalNombre: "SEVILLA",
    LocalResultado: 1,
    VisitanteEscudo: "/images/BayernMunchen.png",
    VisitanteNombre: "BAYERN MUNICH",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PSG",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Chelsea.png",
    VisitanteNombre: "CHELSEA",
    VisitanteResultado: 1,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/SSC_Neapel.svg.png",
    LocalNombre: "NAPOLI",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Zenit.png",
    VisitanteNombre: "ZENIT",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/Tottenham.png",
    LocalNombre: "TOTTENHAM",
    LocalResultado: 1,
    VisitanteEscudo: "/images/AstonVilla.png",
    VisitanteNombre: "ASTON VILLA",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/ManchesterCity.png",
    LocalNombre: "MAN. CITY",
    LocalResultado: 1,
    VisitanteEscudo: "/images/ASRoma.png",
    VisitanteNombre: "ROMA",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/ManchesterUnited.png",
    LocalNombre: "MAN. UNITED",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Valencia.jpg",
    VisitanteNombre: "VALENCIA",
    VisitanteResultado: 2,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PSG",
    LocalResultado: 0,
    VisitanteEscudo: "/images/AstonVilla.png",
    VisitanteNombre: "ASTON VILLA",
    VisitanteResultado: 0,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/Sevilla.webp",
    LocalNombre: "SEVILLA",
    LocalResultado: 1,
    VisitanteEscudo: "/images/ManchesterCity.png",
    VisitanteNombre: "MAN. CITY",
    VisitanteResultado: 2,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PSG",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Juventus.jpg",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 1,
  },
  {
    Player1: "F",
    Player2: "G",
    Result: "L",
    LocalEscudo: "/images/BayernMunchen.png",
    LocalNombre: "BAYERN MUNICH",
    LocalResultado: 2,
    VisitanteEscudo: "/images/RealMadrid.png",
    VisitanteNombre: "REAL MADRID",
    VisitanteResultado: 1,
  },
  {
    Player1: "G",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/RealMadrid.png",
    LocalNombre: "REAL MADRID",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Internazionale.png",
    VisitanteNombre: "INTER",
    VisitanteResultado: 0,
  },
], 
best_match: [
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/SportingLisboa.png",
    LocalNombre: "SPORTING",
    LocalResultado: 5,
    VisitanteEscudo: "/images/SanLorenzo.png",
    VisitanteNombre: "SAN LORENZO",
    VisitanteResultado: 4,
  },
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PSG",
    LocalResultado: 3,
    VisitanteEscudo: "/images/Chelsea.png",
    VisitanteNombre: "CHELSEA",
    VisitanteResultado: 2,
  },
],
torneos: [
  {
    Player1: "F",
    Player2: "M",
    Result: "L",
    LocalEscudo: "/images/ParisSaintGermain.png",
    LocalNombre: "PARIS SAINT GERMAIN",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Chelsea.png",
    VisitanteNombre: "CHELSEA",
    VisitanteResultado: 0,
  },
  {
    Player1: "G",
    Player2: "F",
    Result: "L",
    LocalEscudo: "/images/BayernMunchen.png",
    LocalNombre: "BAYERN MUNICH",
    LocalResultado: 1,
    VisitanteEscudo: "/images/ManchesterCity.png",
    VisitanteNombre: "MANCHESTER CITY",
    VisitanteResultado: 0,
  },
]
}

export const stats_marcos = {
finals : {

matchs : [
  {
    Result: "X",
    LocalEscudo: "/images/internazionale.png",
    LocalNombre: 'INTER',
    LocalResultado: 0,
    VisitanteEscudo: "/images/RealMadrid.png",
    VisitanteNombre: 'REAL MADRID',
    VisitanteResultado: 3,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Valencia.jpg",
    LocalNombre: 'VALENCIA',
    LocalResultado: 2,
    VisitanteEscudo: "/images/ManchesterUnited.png",
    VisitanteNombre: 'MAN. UNITED',
    VisitanteResultado: 3,
  },
  {
    Result: "X",
    LocalEscudo: "/images/AstonVilla.png",
    LocalNombre: 'ASTON VILLA',
    LocalResultado: 0,
    VisitanteEscudo: "/images/Tottenham.png",
    VisitanteNombre: 'TOTTENHAM',
    VisitanteResultado: 1,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Zenit.png",
    LocalNombre: 'ZENIT',
    LocalResultado: 0,
    VisitanteEscudo: "/images/SSC_Neapel.svg.png",
    VisitanteNombre: 'NAPOLI',
    VisitanteResultado: 2,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: 'CHELSEA',
    LocalResultado: 1,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: 'PSG',
    VisitanteResultado: 2,
  },
  {
    Result: "V",
    LocalEscudo: "/images/Valencia.jpg",
    LocalNombre: 'VALENCIA',
    LocalResultado: 1,
    VisitanteEscudo: "/images/Arsenal.jpg",
    VisitanteNombre: 'ARSENAL',
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    VisitanteEscudo: "/images/internazionale.png",
    VisitanteNombre: 'INTER',
    VisitanteResultado: 3,
    LocalEscudo: "/images/Ajax.png",
    LocalNombre: 'AJAX',
    LocalResultado: 1,
  },
  {
    Result: "X",
    VisitanteEscudo: "/images/Liverpool.png",
    VisitanteNombre: 'LIVERPOOL',
    VisitanteResultado: 2,
    LocalEscudo: "/images/Porto.jpg",
    LocalNombre: 'PORTO',
    LocalResultado: 1,
  },
  {
    Result: "X",
    VisitanteEscudo: "/images/Barcelona.webp",
    VisitanteNombre: 'BARCELONA',
    VisitanteResultado: 0,
    LocalEscudo: "/images/Milan.png",
    LocalNombre: 'MILAN',
    LocalResultado: 0,
  },
  {
    Result: "X",
    VisitanteEscudo: "/images/Arsenal.jpg",
    VisitanteNombre: 'ARSENAL',
    VisitanteResultado: 3,
    LocalEscudo: "/images/internazionale.png",
    LocalNombre: 'INTER',
    LocalResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/RealMadrid.png",
    LocalNombre: 'REAL MADRID',
    LocalResultado: 0,
    VisitanteEscudo: "/images/BayernMunchen.png",
    VisitanteNombre: 'BAYERN MUN',
    VisitanteResultado: 1,
  },
  {
    Result: "V",
    LocalEscudo: "/images/RealMadrid.png",
    LocalNombre: 'REAL MADRID',
    LocalResultado: 2,
    VisitanteEscudo: "/images/BayernMunchen.png",
    VisitanteNombre: 'BAYERN MUN',
    VisitanteResultado: 2,
  },
  {
    Result: "V",
    LocalEscudo: "/images/VillaReal.webp",
    LocalNombre: 'VILLA REAL',
    LocalResultado: 1,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: 'PSG',
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Tottenham.png",
    LocalNombre: 'TOTTENHAM',
    LocalResultado: 0,
    VisitanteEscudo: "/images/Liverpool.png",
    VisitanteNombre: 'LIVERPOOL',
    VisitanteResultado: 1,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Zenit.png",
    LocalNombre: 'ZENIT',
    LocalResultado: 0,
    VisitanteEscudo: "/images/Newcastle.png",
    VisitanteNombre: 'NEWCASTLE',
    VisitanteResultado: 1,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Arsenal.jpg",
    LocalNombre: 'ARSENAL',
    LocalResultado: 0,
    VisitanteEscudo: "/images/Ajax.png",
    VisitanteNombre: 'AJAX',
    VisitanteResultado: 3,
  },
  {
    Result: "V",
    LocalEscudo: "/images/ManchesterUnited.png",
    LocalNombre: 'MANCHESTER UNITED',
    LocalResultado: 1,
    VisitanteEscudo: "/images/Liverpool.png",
    VisitanteNombre: 'LIVERPOOL',
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: 'CHELSEA',
    LocalResultado: 2,
    VisitanteEscudo: "/images/Barcelona.webp",
    VisitanteNombre: 'BARCELONA',
    VisitanteResultado: 2,
  },
  {
    Result: "V",
    LocalEscudo: "/images/RealMadrid.png",
    LocalNombre: 'REAL MADRID',
    LocalResultado: 1,
    VisitanteEscudo: "/images/Tottenham.png",
    VisitanteNombre: 'TOTTENHAM',
    VisitanteResultado: 0,
  },
  {
    Result: "V",
    LocalEscudo: "/images/Tottenham.png",
    LocalNombre: 'TOTTENHAM',
    LocalResultado: 2,
    VisitanteEscudo: "/images/Arsenal.jpg",
    VisitanteNombre: 'ARSENAL',
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/BayernMunchen.png",
    LocalNombre: 'BAYERN MUNICH',
    LocalResultado: 0,
    VisitanteEscudo: "/images/Porto.jpg",
    VisitanteNombre: 'PORTO',
    VisitanteResultado: 1,
  },
],
  stats: {
    win: 6,
    loss: 14,
    porcent: "30%",
  }
},
clasics : {
  matchs : [
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 2,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PSG",
    VisitanteResultado: 3,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 1,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PSG",
    VisitanteResultado: 2,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PSG",
    VisitanteResultado: 2,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PSG",
    VisitanteResultado: 2,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 1,
    VisitanteEscudo: "/images/ParisSaintGermain.png",
    VisitanteNombre: "PSG",
    VisitanteResultado: 3,
  },
  {
    Result: "V",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Juventus.png",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Juventus.png",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 2,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Juventus.png",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
  {
    Result: "X",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 0,
    VisitanteEscudo: "/images/Juventus.png",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
  {
    Result: "V",
    LocalEscudo: "/images/Chelsea.png",
    LocalNombre: "CHELSEA",
    LocalResultado: 2,
    VisitanteEscudo: "/images/Juventus.png",
    VisitanteNombre: "JUVENTUS",
    VisitanteResultado: 0,
  },
],
  stats: {
    win: 1,
    loss: 5,
    porcent: "16%",
  }
}
}

export const stats_franco = { 
  finals : { 
    matchs: [ 
      
          {
            Result: 'V',
            LocalEscudo: '/images/BayernMunchen.png',
            LocalNombre: 'BAYERN MUN',
            LocalResultado: 2,
            VisitanteEscudo: '/images/RealMadrid.png',
            VisitanteNombre: 'REAL MADRID',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 3,
            VisitanteEscudo: '/images/Juventus.png',
            VisitanteNombre: 'JUVENTUS',
            VisitanteResultado: 1
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Sevilla.webp',
            LocalNombre: 'SEVILLA',
            LocalResultado: 1,
            VisitanteEscudo: '/images/ManchesterCity.png',
            VisitanteNombre: 'MAN. CITY',
            VisitanteResultado: 2
          },
          {
            Result: 'X',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 0,
            VisitanteEscudo: '/images/AstonVilla.png',
            VisitanteNombre: 'ASTON VILLA',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ManchesterCity.png',
            LocalNombre: 'MAN. CITY',
            LocalResultado: 1,
            VisitanteEscudo: '/images/ASRoma.png',
            VisitanteNombre: 'ROMA',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ManchesterUnited.png',
            LocalNombre: 'MAN. UNITED',
            LocalResultado: 3,
            VisitanteEscudo: '/images/Valencia.jpg',
            VisitanteNombre: 'VALENCIA',
            VisitanteResultado: 2
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Tottenham.png',
            LocalNombre: 'TOTTENHAM',
            LocalResultado: 1,
            VisitanteEscudo: '/images/AstonVilla.png',
            VisitanteNombre: 'ASTON VILLA',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 2,
            VisitanteEscudo: '/images/Chelsea.png',
            VisitanteNombre: 'CHELSEA',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Sevilla.webp',
            LocalNombre: 'SEVILLA',
            LocalResultado: 1,
            VisitanteEscudo: '/images/BayernMunchen.png',
            VisitanteNombre: 'BAYERN MUN',
            VisitanteResultado: 0
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Arsenal.jpg',
            LocalNombre: 'ARSENAL',
            LocalResultado: 0,
            VisitanteEscudo: '/images/Valencia.jpg',
            VisitanteNombre: 'VALENCIA',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/internazionale.png',
            LocalNombre: 'INTER',
            LocalResultado: 3,
            VisitanteEscudo: '/images/Ajax.png',
            VisitanteNombre: 'AJAX',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Barcelona.webp',
            LocalNombre: 'BARCELONA',
            LocalResultado: 0,
            VisitanteEscudo: '/images/Milan.png',
            VisitanteNombre: 'MILAN',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 2,
            VisitanteEscudo: '/images/Juventus.png',
            VisitanteNombre: 'JUVENTUS',
            VisitanteResultado: 0
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Liverpool.png',
            LocalNombre: 'LIVERPOOL',
            LocalResultado: 1,
            VisitanteEscudo: '/images/Juventus.png',
            VisitanteNombre: 'JUVENTUS',
            VisitanteResultado: 2
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 4,
            VisitanteEscudo: '/images/Milan.png',
            VisitanteNombre: 'MILAN',
            VisitanteResultado: 2
          },
          {
            Result: 'X',
            LocalEscudo: '/images/ParisSaintGermain.png',
            LocalNombre: 'PSG',
            LocalResultado: 0,
            VisitanteEscudo: '/images/VillaReal.webp',
            VisitanteNombre: 'VILLA REAL',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Liverpool.png',
            LocalNombre: 'LIVERPOOL',
            LocalResultado: 1,
            VisitanteEscudo: '/images/Tottenham.png',
            VisitanteNombre: 'TOTTENHAM',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Newcastle.png',
            LocalNombre: 'NEWCLASTLE',
            LocalResultado: 1,
            VisitanteEscudo: '/images/Zenit.png',
            VisitanteNombre: 'ZENIT',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/ManchesterUnited.png',
            LocalNombre: 'MAN. UNITED',
            LocalResultado: 1,
            VisitanteEscudo: '/images/Juventus.png',
            VisitanteNombre: 'JUVENTUS',
            VisitanteResultado: 0
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Ajax.png',
            LocalNombre: 'AJAX',
            LocalResultado: 3,
            VisitanteEscudo: '/images/Arsenal.jpg',
            VisitanteNombre: 'ARSENAL',
            VisitanteResultado: 0
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Liverpool.png',
            LocalNombre: 'LIVERPOOL',
            LocalResultado: 0,
            VisitanteEscudo: '/images/ManchesterUnited.png',
            VisitanteNombre: 'MANCHESTER UNITED',
            VisitanteResultado: 1
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Porto.jpg',
            LocalNombre: 'PORTO',
            LocalResultado: 0,
            VisitanteEscudo: '/images/ManchesterCity.png',
            VisitanteNombre: 'MANCHESTER CITY',
            VisitanteResultado: 1
          },
          {
            Result: 'V',
            LocalEscudo: '/images/Barcelona.webp',
            LocalNombre: 'BARCELONA',
            LocalResultado: 2,
            VisitanteEscudo: '/images/Chelsea.png',
            VisitanteNombre: 'CHELSEA',
            VisitanteResultado: 2
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Arsenal.jpg',
            LocalNombre: 'ARSENAL',
            LocalResultado: 0,
            VisitanteEscudo: '/images/Tottenham.png',
            VisitanteNombre: 'TOTTENHAM',
            VisitanteResultado: 2
          },
          {
            Result: 'X',
            LocalEscudo: '/images/Valencia.jpg',
            LocalNombre: 'VALENCIA',
            LocalResultado: 1,
            VisitanteEscudo: '/images/Newcastle.png',
            VisitanteNombre: 'NEWCASTLE',
            VisitanteResultado: 3
          }, 
    ],
    stats: {
      win: 16,
      loss: 9,
      porcent: "64%",
    }
  },
  clasics: {
    matchs: [
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 3,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 2
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 3,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Juventus.png',
        VisitanteNombre: 'JUVENTUS',
        VisitanteResultado: 2
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 3,
        VisitanteEscudo: '/images/Juventus.png',
        VisitanteNombre: 'JUVENTUS',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Juventus.png',
        VisitanteNombre: 'JUVENTUS',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Juventus.png',
        VisitanteNombre: 'JUVENTUS',
        VisitanteResultado: 1
      },
      {
        Result: 'X',
        LocalEscudo: '/images/ParisSaintGermain.png',
        LocalNombre: 'PSG',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Juventus.png',
        VisitanteNombre: 'JUVENTUS',
        VisitanteResultado: 0
      }
    ],
    stats: {
      porcent: "85%",
      win:6,
      loss:1 ,
    }
  }
}

export const stats_gaston = { 
  finals: {
    matchs: [
      {
        Result: 'V',
        LocalEscudo: '/images/RealMadrid.png',
        LocalNombre: 'REAL MADRID',
        LocalResultado: 3,
        VisitanteEscudo: '/images/internazionale.png',
        VisitanteNombre: 'INTER',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/RealMadrid.png',
        LocalNombre: 'REAL MADRID',
        LocalResultado: 1,
        VisitanteEscudo: '/images/BayernMunchen.png',
        VisitanteNombre: 'BAYERN MUN',
        VisitanteResultado: 2
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 1,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 3
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ManchesterCity.png',
        LocalNombre: 'MAN. CITY',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Sevilla.webp',
        VisitanteNombre: 'SEVILLA',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/AstonVilla.png',
        LocalNombre: 'ASTON VILLA',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/ASRoma.png',
        LocalNombre: 'ROMA',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ManchesterCity.png',
        VisitanteNombre: 'MAN. CITY',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/SSC_Neapel.svg.png',
        LocalNombre: 'NAPOLI',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Zenit.png',
        VisitanteNombre: 'ZENIT',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/BayernMunchen.png',
        LocalNombre: 'BAYERN MUN',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Sevilla.webp',
        VisitanteNombre: 'SEVILLA',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Porto.jpg',
        LocalNombre: 'PORTO',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Liverpool.png',
        VisitanteNombre: 'LIVERPOOL',
        VisitanteResultado: 1
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 2
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Arsenal.jpg',
        LocalNombre: 'ARSENAL',
        LocalResultado: 3,
        VisitanteEscudo: '/images/internazionale.png',
        VisitanteNombre: 'INTER',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Liverpool.png',
        VisitanteNombre: 'LIVERPOOL',
        VisitanteResultado: 1
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Milan.png',
        LocalNombre: 'MILAN',
        LocalResultado: 2,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 4
      },
      {
        Result: 'V',
        LocalEscudo: '/images/BayernMunchen.png',
        LocalNombre: 'BAYERN MUN',
        LocalResultado: 1,
        VisitanteEscudo: '/images/RealMadrid.png',
        VisitanteNombre: 'REALMADRID',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/BayernMunchen.png',
        LocalNombre: 'BAYERN MUN',
        LocalResultado: 2,
        VisitanteEscudo: '/images/RealMadrid.png',
        VisitanteNombre: 'REAL MADRID',
        VisitanteResultado: 2
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ManchesterUnited.png',
        VisitanteNombre: 'MANCHESTER UN',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/ManchesterCity.png',
        LocalNombre: 'MANCHESTER CITY',
        LocalResultado: 1,
        VisitanteEscudo: '/images/Porto.jpg',
        VisitanteNombre: 'PORTO',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Tottenham.png',
        LocalNombre: 'TOTTENHAM',
        LocalResultado: 0,
        VisitanteEscudo: '/images/RealMadrid.png',
        VisitanteNombre: 'REAL MADRID',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Newcastle.png',
        LocalNombre: 'NEWCASTLE',
        LocalResultado: 3,
        VisitanteEscudo: '/images/Valencia.jpg',
        VisitanteNombre: 'VALENCIA',
        VisitanteResultado: 1
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Porto.jpg',
        LocalNombre: 'PORTO',
        LocalResultado: 1,
        VisitanteEscudo: '/images/BayernMunchen.png',
        VisitanteNombre: 'BAYERN MUNICH',
        VisitanteResultado: 0
      },
    ],
    stats: {
      win: 11,
      loss: 9,
      porcent: "55%",
    },
  },
  clasics: {
    matchs: [
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 2,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 0
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/Chelsea.png',
        VisitanteNombre: 'CHELSEA',
        VisitanteResultado: 2
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 2,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 2
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 1,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 3
      },
      {
        Result: 'X',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 2
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 1,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 0
      },
      {
        Result: 'V',
        LocalEscudo: '/images/Juventus.png',
        LocalNombre: 'JUVENTUS',
        LocalResultado: 0,
        VisitanteEscudo: '/images/ParisSaintGermain.png',
        VisitanteNombre: 'PSG',
        VisitanteResultado: 0
      }
    ],
    stats: {
      win: 3,
      loss: 4,
      porcent: "42%",
    },
}
}

export const data = {
  poster: [
   {
    image: "https://st1.uvnimg.com/f0/b8/159a38194e579b74a942b8c10008/gettyimages-1149331608.jpg",
    alt: "poster_image",
    title: "AJAX CAMPEON",
    description: "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
   },
   {
    image: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1440,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/AC-Monaco-v-Porto---UEFA-Champions-League-Final-5f05fd3c5c1c440351f6f19748a748b0.jpg",
    alt: "poster_image",
    title: "PORTO SUMA SU SEGUNDO TITULO",
    description: "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
   },
   {
    image: " https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt258bc4e87ba31646/658ebd9dd7a29304077f8b4f/Goal_HIC_-_LinkedIn_(75).png?auto=webp&format=pjpg&width=3840&quality=60",
    alt: "poster_image",
    title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
    description: "Galatasaray jugara el torneo la proxima copa.",
   },
   {
    image: "https://newsmedia.tasnimnews.com/Tasnim/Uploaded/Image/1400/02/04/1400020400192581422620774.jpg",
    alt: "poster_image",
    title: "AL NASSAR PIERDE LA CATEGORIA",
    description: "Al Nassar eliminado del torneo, baja de categoria.",
   },
  ],
  new: [
    {
      image: "https://st1.uvnimg.com/f0/b8/159a38194e579b74a942b8c10008/gettyimages-1149331608.jpg",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description: "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
     },
     {
      image: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1440,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/AC-Monaco-v-Porto---UEFA-Champions-League-Final-5f05fd3c5c1c440351f6f19748a748b0.jpg",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description: "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
     },
     {
      image: " https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt258bc4e87ba31646/658ebd9dd7a29304077f8b4f/Goal_HIC_-_LinkedIn_(75).png?auto=webp&format=pjpg&width=3840&quality=60",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
     },
     {
      image: "https://newsmedia.tasnimnews.com/Tasnim/Uploaded/Image/1400/02/04/1400020400192581422620774.jpg",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
     },
  
  ],
  ranking: [
    {
      logo: "images/ParisSaintGermain.png",
      rank: 1,
      name: "PARIS SAINT GERMAIN",
      titles: 4,
    },
    {
      logo: "images/BayernMunchen.png",
      rank: 2,
      name: "BAYERN MUNICH",
      titles: 3,
    },
    {
      logo: "images/ManchesterUnited.png",
      rank: 3,
      name: "MANCHESTER UNITED",
      titles: 3,
    },
    {
      logo: "images/ManchesterCity.png",
      rank: 4,
      name: "MANCHESTER CITY",
      titles: 3,
    },
    {
      logo: "images/RealMadrid.png",
      rank: 5,
      name: "REAL MADRID",
      titles: 3,
    },
    {
      logo: "images/Barcelona.webp",
      rank: 6,
      name: "BARCELONA",
      titles: 2,
    },
    {
      logo: "images/Tottenham.png",
      rank: 7,
      name: "TOTTENHAM",
      titles: 2,
    },
    {
      logo: "images/Newcastle.png",
      rank: 8,
      name: "NEWCASTLE",
      titles: 2,
    },
    {
      logo: "images/Porto.jpg",
      rank: 9,
      name: "PORTO",
      titles: 2,
    },
    {
      logo: "images/AstonVilla.png",
      rank: 10,
      name: "ASTON VILLA",
      titles: 1,
    },
    {
      logo: "images/SSC_Neapel.svg.png",
      rank: 11,
      name: "NAPOLI",
      titles: 1,
    },
    {
      logo: "images/Sevilla.webp",
      rank: 12,
      name: "SEVILLA",
      titles: 1,
    },
    {
      logo: "images/Valencia.jpg",
      rank: 13,
      name: "VALENCIA",
      titles: 1,
    },
    {
      logo: "images/Internazionale.png",
      rank: 14,
      name: "INTER",
      titles: 1,
    },
    {
      logo: "images/Arsenal.jpg",
      rank: 15,
      name: "ARSENAL",
      titles: 1,
    },
    {
      logo: "images/Juventus.png",
      rank: 16,
      name: "JUVENTUS",
      titles: 1,
    },
    {
      logo: "images/VillaReal.webp",
      rank: 17,
      name: "VILLA REAL",
      titles: 1,
    },
    {
      logo: "images/Liverpool.png",
      rank: 18,
      name: "LIVERPOOL",
      titles: 1,
    },
    {
      logo: "images/Ajax.png",
      rank: 19,
      name: "AJAX",
      titles: 1,
    },
    {
      logo: "images/Chelsea.png",
      rank: 20,
      name: "CHELSEA",
      titles: 0,
    },
    {
      logo: "images/Zenit.png",
      rank: 21,
      name: "ZENIT",
      titles: 0,
    },
    {
      logo: "images/Milan.png",
      rank: 22,
      name: "AC MILAN",
      titles: 0,
    },
    {
      logo: "images/BorussiaDortmund.png",
      rank: 23,
      name: "BORUSSIA DORTMUND",
      titles: 0,
    },
    {
      logo: "images/SportingLisboa.png",
      rank: 24,
      name: "SPORTING LISBOA",
      titles: 0,
    },
    {
      logo: "images/Lazio.png",
      rank: 25,
      name: "LAZIO",
      titles: 0,
    },
    {
      logo: "images/AtleticoMadrid.png",
      rank: 26,
      name: "ATL. MADRID",
      titles: 0,
    },
    {
      logo: "images/Everton.png",
      rank: 27,
      name: "EVERTON",
      titles: 0,
    },
    {
      logo: "images/ASRoma.png",
      rank: 28,
      name: "AS ROMA",
      titles: 0,
    },
    {
      logo: "images/Benfica.png",
      rank: 29,
      name: "BENFICA",
      titles: 0,
    },
    {
      logo: "images/wolfburgo.png",
      rank: 30,
      name: "WOLFSBURGO",
      titles: 0,
    },
    {
      logo: "images/fiorentina.png",
      rank: 31,
      name: "FIORENTINA",
      titles: 0,
    },
    {
      logo: "images/Lyon.png",
      rank: 32,
      name: "LYON",
      titles: 0,
    },
  ]
}