export const History = {
  Games: [
    {
      Player1: "M",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/Chelsea.png",
      LocalNombre: "CHELSEA",
      LocalResultado: 2,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteResultado: 1,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/BorussiaDortmund.png",
      LocalNombre: "BORUSSIA DORTMUND",
      LocalResultado: "1 (6)",
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteResultado: "1 (7)",
    },
    {
      Player1: "G",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalResultado: 0,
      VisitanteEscudo: "/images/ParisSaintGermain.png",
      VisitanteNombre: "PARIS SAINT GERMAIN",
      VisitanteResultado: 1,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "NO",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalResultado: 1,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteResultado: 0,
    },
    {
      Player1: "G",
      Player2: "F",
      Result: "NO",
      LocalEscudo: "/images/newcastlee.png",
      LocalNombre: "NEWCASTLE",
      LocalResultado: 3,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteResultado: 1,
    },
    {
      Player1: "M",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/Tottenham.png",
      LocalNombre: "TOTTENHAM",
      LocalResultado: 2,
      VisitanteEscudo: "/images/arsenalfc.png",
      VisitanteNombre: "ARSENAL",
      VisitanteResultado: 0,
    },
    {
      Player1: "M",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/RealMadrid.png",
      LocalNombre: "REAL MADRID",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Tottenham.png",
      VisitanteNombre: "TOTTENHAM",
      VisitanteResultado: 0,
    },
    {
      Player1: "M",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/Chelsea.png",
      LocalNombre: "CHELSEA",
      LocalResultado: "2 (4)",
      VisitanteEscudo: "/images/Barcelona.webp",
      VisitanteNombre: "BARCELONA",
      VisitanteResultado: "2 (5)",
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalResultado: 0,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteResultado: 1,
    },
    {
      Player1: "M",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Liverpool.png",
      VisitanteNombre: "LIVERPOOL",
      VisitanteResultado: 0,
    },

    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/Ajax.png",
      LocalNombre: "AJAX",
      LocalResultado: 3,
      VisitanteEscudo: "/images/arsenalfc.png",
      VisitanteNombre: "ARSENAL",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalResultado: 1,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/newcastlee.png",
      LocalNombre: "NEWCASTLE",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Zenit.png",
      VisitanteNombre: "ZENIT",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/Liverpool.png",
      LocalNombre: "LIVERPOOL",
      LocalResultado: 1,
      VisitanteEscudo: "/images/Tottenham.png",
      VisitanteNombre: "TOTTENHAM",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "NO",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 0,
      VisitanteEscudo: "/images/villar.png",
      VisitanteNombre: "VILLA REAL",
      VisitanteResultado: 1,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalResultado: "2 (3)",
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteResultado: "2 (5)",
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalResultado: 1,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteResultado: 0,
    },
    {
      Player1: "G",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/Milan.png",
      LocalNombre: "AC MILAN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/ParisSaintGermain.png",
      VisitanteNombre: "PARIS SAINT GERMAIN",
      VisitanteResultado: 4,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/Liverpool.png",
      LocalNombre: "LIVERPOOL",
      LocalResultado: 1,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteResultado: 2,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteResultado: 0,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/arsenalfc.png",
      LocalNombre: "ARSENAL",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/Barcelona.webp",
      LocalNombre: "BARCELONA",
      LocalResultado: "0 (4)",
      VisitanteEscudo: "/images/Milan.png",
      VisitanteNombre: "AC MILAN",
      VisitanteResultado: "0 (2)",
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "NO",
      LocalEscudo: "/images/oporto.png",
      LocalNombre: "PORTO",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Liverpool.png",
      VisitanteNombre: "LIVERPOOL",
      VisitanteResultado: 1,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "NO",
      LocalEscudo: "/images/Internazionale.png",
      LocalNombre: "INTER",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Ajax.png",
      VisitanteNombre: "AJAX",
      VisitanteResultado: 1,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/arsenalfc.png",
      LocalNombre: "ARSENAL",
      LocalResultado: 0,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteResultado: 1,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/sevillaa.png",
      LocalNombre: "SEVILLA",
      LocalResultado: 1,
      VisitanteEscudo: "/images/BayernMunchen.png",
      VisitanteNombre: "BAYERN MUNICH",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteResultado: 1,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/SSC_Neapel.svg.png",
      LocalNombre: "NAPOLI",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Zenit.png",
      VisitanteNombre: "ZENIT",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/Tottenham.png",
      LocalNombre: "TOTTENHAM",
      LocalResultado: 1,
      VisitanteEscudo: "/images/AstonVilla.png",
      VisitanteNombre: "ASTON VILLA",
      VisitanteResultado: 0,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/mancity.png",
      LocalNombre: "MANCHESTER CITY",
      LocalResultado: 1,
      VisitanteEscudo: "/images/ASRoma.png",
      VisitanteNombre: "ROMA",
      VisitanteResultado: 0,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ManchesterUnited.png",
      LocalNombre: "MANCHESTER UNITED",
      LocalResultado: 3,
      VisitanteEscudo: "/images/valenciafc.png",
      VisitanteNombre: "VALENCIA",
      VisitanteResultado: 2,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: "0 (4)",
      VisitanteEscudo: "/images/AstonVilla.png",
      VisitanteNombre: "ASTON VILLA",
      VisitanteResultado: "0 (5)",
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/sevillaa.png",
      LocalNombre: "SEVILLA",
      LocalResultado: 1,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MAN. CITY",
      VisitanteResultado: 2,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 3,
      VisitanteEscudo: "/images/da-removebg-preview.png",
      VisitanteNombre: "JUVENTUS",
      VisitanteResultado: 1,
    },
    {
      Player1: "F",
      Player2: "G",
      Result: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalResultado: 2,
      VisitanteEscudo: "/images/RealMadrid.png",
      VisitanteNombre: "REAL MADRID",
      VisitanteResultado: 1,
    },
    {
      Player1: "G",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/RealMadrid.png",
      LocalNombre: "REAL MADRID",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Internazionale.png",
      VisitanteNombre: "INTER",
      VisitanteResultado: 0,
    },
  ],
  best_match: [
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/SportingLisboa.png",
      LocalNombre: "SPORTING",
      LocalResultado: 5,
      VisitanteEscudo: "/images/SanLorenzo.png",
      VisitanteNombre: "SAN LORENZO",
      VisitanteResultado: 4,
    },
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 3,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteResultado: 2,
    },
  ],
  torneos: [
    {
      Player1: "F",
      Player2: "M",
      Result: "L",
      LocalEscudo: "/images/ParisSaintGermain.png",
      LocalNombre: "PARIS SAINT GERMAIN",
      LocalResultado: 2,
      VisitanteEscudo: "/images/Chelsea.png",
      VisitanteNombre: "CHELSEA",
      VisitanteResultado: 0,
    },
    {
      Player1: "G",
      Player2: "F",
      Result: "L",
      LocalEscudo: "/images/BayernMunchen.png",
      LocalNombre: "BAYERN MUNICH",
      LocalResultado: 1,
      VisitanteEscudo: "/images/mancity.png",
      VisitanteNombre: "MANCHESTER CITY",
      VisitanteResultado: 0,
    },
  ],
};

export const stats_marcos = {
  finals: {
    matchs: [
      {
        Result: "Defeat",
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalResultado: 0,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteResultado: 3,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MAN. UNITED",
        VisitanteResultado: 3,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/AstonVilla.png",
        LocalNombre: "ASTON VILLA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Zenit.png",
        LocalNombre: "ZENIT",
        LocalResultado: 0,
        VisitanteEscudo: "/images/SSC_Neapel.svg.png",
        VisitanteNombre: "NAPOLI",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteResultado: 3,
        LocalEscudo: "/images/Ajax.png",
        LocalNombre: "AJAX",
        LocalResultado: 1,
      },
      {
        Result: "Defeat",
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteResultado: 2,
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalResultado: 1,
      },
      {
        Result: "Defeat",
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteResultado: 0,
        LocalEscudo: "/images/Milan.png",
        LocalNombre: "MILAN",
        LocalResultado: 0,
      },
      {
        Result: "Defeat",
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteResultado: 3,
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalResultado: 0,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUN",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalResultado: 2,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUN",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/villar.png",
        LocalNombre: "VILLA REAL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Zenit.png",
        LocalNombre: "ZENIT",
        LocalResultado: 0,
        VisitanteEscudo: "/images/newcastlee.png",
        VisitanteNombre: "NEWCASTLE",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Ajax.png",
        VisitanteNombre: "AJAX",
        VisitanteResultado: 3,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Barcelona.webp",
        VisitanteNombre: "BARCELONA",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalResultado: 2,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUNICH",
        LocalResultado: 0,
        VisitanteEscudo: "/images/oporto.png",
        VisitanteNombre: "PORTO",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: "1 (7)",
        VisitanteEscudo: "/images/BorussiaDortmund.png",
        VisitanteNombre: "BORUSSIA DORTMUND",
        VisitanteResultado: "1 (6)",
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteResultado: 1,
      },
    ],
    stats: {
      win: 8,
      loss: 14,
      porcent: "36%",
    },
  },
  clasics: {
    matchs: [
      {
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 3,
      },
      {
        Result: "Defeat",
        Raiz: "Final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "Final - Verano",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "16avos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 3,
      },
      {
        Result: "Victory",
        Raiz: "16avos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Draw",
        Raiz: "Amistoso",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "Fase Grupos - Verano",
        LocalEscudo: "/images/Chelsea.png",
        LocalNombre: "CHELSEA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
    ],
    stats: {
      win: 2,
      loss: 7,
      draw: 1,
      porcent: "20%",
    },
  },
};

export const stats_franco = {
  finals: {
    matchs: [
      {
        Result: "Victory",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUN",
        LocalResultado: 2,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/sevillaa.png",
        LocalNombre: "SEVILLA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MAN. CITY",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/AstonVilla.png",
        VisitanteNombre: "ASTON VILLA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MAN. CITY",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ASRoma.png",
        VisitanteNombre: "ROMA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MAN. UNITED",
        LocalResultado: 3,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalResultado: 1,
        VisitanteEscudo: "/images/AstonVilla.png",
        VisitanteNombre: "ASTON VILLA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/sevillaa.png",
        LocalNombre: "SEVILLA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUN",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/internazionale.png",
        LocalNombre: "INTER",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Ajax.png",
        VisitanteNombre: "AJAX",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Milan.png",
        VisitanteNombre: "MILAN",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 4,
        VisitanteEscudo: "/images/Milan.png",
        VisitanteNombre: "MILAN",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/villar.png",
        VisitanteNombre: "VILLA REAL",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/newcastlee.png",
        LocalNombre: "NEWCLASTLE",
        LocalResultado: 1,
        VisitanteEscudo: "/images/Zenit.png",
        VisitanteNombre: "ZENIT",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MAN. UNITED",
        LocalResultado: 1,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Ajax.png",
        LocalNombre: "AJAX",
        LocalResultado: 3,
        VisitanteEscudo: "/images/arsenalfc.png",
        VisitanteNombre: "ARSENAL",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Liverpool.png",
        LocalNombre: "LIVERPOOL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalResultado: 0,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MANCHESTER CITY",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/Barcelona.webp",
        LocalNombre: "BARCELONA",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Tottenham.png",
        VisitanteNombre: "TOTTENHAM",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/valenciafc.png",
        LocalNombre: "VALENCIA",
        LocalResultado: 1,
        VisitanteEscudo: "/images/newcastlee.png",
        VisitanteNombre: "NEWCASTLE",
        VisitanteResultado: 3,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PARIS SAINT GERMAIN",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UNITED",
        VisitanteResultado: 0,
      },
    ],
    stats: {
      win: 17,
      loss: 9,
      porcent: "66%",
    },
  },
  clasics: {
    matchs: [
      {
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        Raiz: "Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "Final - Verano",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "16avos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        Raiz: "Final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 3,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 2,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 1,
      },
      {
        Result: "Draw",
        Raiz: "Fase de grupos - Verano",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        Raiz: "16Avos",
        LocalEscudo: "/images/ParisSaintGermain.png",
        LocalNombre: "PSG",
        LocalResultado: 0,
        VisitanteEscudo: "/images/da-removebg-preview.png",
        VisitanteNombre: "JUVENTUS",
        VisitanteResultado: 1,
      },
    ],
    stats: {
      porcent: "76%",
      win: 8,
      loss: 2,
    },
  },
};

export const stats_gaston = {
  finals: {
    matchs: [
      {
        Result: "Victory",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalResultado: 3,
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/RealMadrid.png",
        LocalNombre: "REAL MADRID",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUN",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 3,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MAN. CITY",
        LocalResultado: 2,
        VisitanteEscudo: "/images/sevillaa.png",
        VisitanteNombre: "SEVILLA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/AstonVilla.png",
        LocalNombre: "ASTON VILLA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/ASRoma.png",
        LocalNombre: "ROMA",
        LocalResultado: 0,
        VisitanteEscudo: "/images/mancity.png",
        VisitanteNombre: "MAN. CITY",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/SSC_Neapel.svg.png",
        LocalNombre: "NAPOLI",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Zenit.png",
        VisitanteNombre: "ZENIT",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUN",
        LocalResultado: 0,
        VisitanteEscudo: "/images/sevillaa.png",
        VisitanteNombre: "SEVILLA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/arsenalfc.png",
        LocalNombre: "ARSENAL",
        LocalResultado: 3,
        VisitanteEscudo: "/images/internazionale.png",
        VisitanteNombre: "INTER",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Liverpool.png",
        VisitanteNombre: "LIVERPOOL",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Milan.png",
        LocalNombre: "MILAN",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 4,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUN",
        LocalResultado: 1,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REALMADRID",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/BayernMunchen.png",
        LocalNombre: "BAYERN MUN",
        LocalResultado: 2,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ManchesterUnited.png",
        VisitanteNombre: "MANCHESTER UN",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/mancity.png",
        LocalNombre: "MANCHESTER CITY",
        LocalResultado: 1,
        VisitanteEscudo: "/images/oporto.png",
        VisitanteNombre: "PORTO",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/Tottenham.png",
        LocalNombre: "TOTTENHAM",
        LocalResultado: 0,
        VisitanteEscudo: "/images/RealMadrid.png",
        VisitanteNombre: "REAL MADRID",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/newcastlee.png",
        LocalNombre: "NEWCASTLE",
        LocalResultado: 3,
        VisitanteEscudo: "/images/valenciafc.png",
        VisitanteNombre: "VALENCIA",
        VisitanteResultado: 1,
      },
      {
        Result: "Victory",
        LocalEscudo: "/images/oporto.png",
        LocalNombre: "PORTO",
        LocalResultado: 1,
        VisitanteEscudo: "/images/BayernMunchen.png",
        VisitanteNombre: "BAYERN MUNICH",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/ManchesterUnited.png",
        LocalNombre: "MANCHESTER UNITED",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PARIS SAINT GERMAIN",
        VisitanteResultado: 1,
      },
      {
        Result: "Defeat",
        LocalEscudo: "/images/BorussiaDortmund.png",
        LocalNombre: "BORUSSIA DORTMUND",
        LocalResultado: "1 (6)",
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: "1 (7)",
      },
    ],
    stats: {
      win: 11,
      loss: 11,
      porcent: "50%",
    },
  },
  clasics: {
    matchs: [
      {
        Result: "Defeat",
        Raiz: "16avos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 2,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "Octavos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Draw",
        Raiz: "Amistoso",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 0,
      },
      {
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/Chelsea.png",
        VisitanteNombre: "CHELSEA",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 2,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Defeat",
        Raiz: "Final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 3,
      },
      {
        Result: "Defeat",
        Raiz: "Cuartos de final",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 2,
      },
      {
        Result: "Victory",
        Raiz: "Semifinal",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 0,
      },
      {
        Result: "Draw",
        Raiz: "Fase de grupos - Verano",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 0,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 0,
      },
      {
        Result: "Victory",
        Raiz: "16Avos",
        LocalEscudo: "/images/da-removebg-preview.png",
        LocalNombre: "JUVENTUS",
        LocalResultado: 1,
        VisitanteEscudo: "/images/ParisSaintGermain.png",
        VisitanteNombre: "PSG",
        VisitanteResultado: 0,
      },
    ],
    stats: {
      win: 4,
      loss: 5,
      porcent: "4   0%",
    },
  },
};

export const data = {
  poster: [
    {
      image: "/images/chelsea_poster.webp",
      alt: "poster_image",
      title: "¡CHELSEA CAMPEON!",
      description:
        "SE LE DIO, Chelsea es el nuevo campeon, vence la final por penales a Dortmund, de la mano de Marcos Aquino.",
    },
    {
      image:
        "/images/ajax_poster.jpg",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image:
        "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image:
        "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image:
        "/images/alnassar_poster.jpg",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
  ],
  new: [
    {
      image: "/images/poster_marcos.jpeg",
      alt: "poster_image",
      title: "¡CHELSEA CAMPEON!",
      description:
        "SE LE DIO, Chelsea es el nuevo campeon, vence la final por penales a Dortmund, de la mano de Marcos Aquino.",
    },
    {
      image:
        "/images/ajax_poster.jpg",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image:
        "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image:
        "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image:
        "/images/alnassar_poster.jpg",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
    {
      image:
        "/images/ajax_poster.jpg",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image:
        "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image:
        "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image:
        "/images/alnassar_poster.jpg",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
    {
      image:
        "/images/ajax_poster.jpg",
      alt: "poster_image",
      title: "AJAX CAMPEON",
      description:
        "Ajax goleo 3 a 0 al ARSENAL, y levanto su primer trofeo, se le acredito la posicion N°19.",
    },
    {
      image:
        "/images/porto_poster.webp",
      alt: "poster_image",
      title: "PORTO SUMA SU SEGUNDO TITULO",
      description:
        "Porto suma una estrella mas, y escala al TOP 9 del ranking mundial, tras derrotar 1 a 0 al Bayern Munich.",
    },
    {
      image:
        "/images/galatasaray_poster.webp",
      alt: "poster_image",
      title: "GALATASARAY ES EL NUEVO PARTICIPANTE DE LOS TORNEOS",
      description: "Galatasaray jugara el torneo la proxima copa.",
    },
    {
      image:
        "/images/alnassar_poster.jpg",
      alt: "poster_image",
      title: "AL NASSAR PIERDE LA CATEGORIA",
      description: "Al Nassar eliminado del torneo, baja de categoria.",
    },
  ],
  ranking: [
    {
      logo: "/images/ParisSaintGermain.png",
      rank: 1,
      name: "PARIS SAINT GERMAIN",
      titles: 5,
    },
    {
      logo: "/images/BayernMunchen.png",
      rank: 2,
      name: "BAYERN MUNICH",
      titles: 3,
    },
    {
      logo: "/images/ManchesterUnited.png",
      rank: 3,
      name: "MANCHESTER UNITED",
      titles: 3,
    },
    {
      logo: "/images/mancity.png",
      rank: 4,
      name: "MANCHESTER CITY",
      titles: 3,
    },
    {
      logo: "/images/RealMadrid.png",
      rank: 5,
      name: "REAL MADRID",
      titles: 3,
    },
    {
      logo: "/images/Barcelona.webp",
      rank: 6,
      name: "BARCELONA",
      titles: 2,
    },
    {
      logo: "/images/Tottenham.png",
      rank: 7,
      name: "TOTTENHAM",
      titles: 2,
    },
    {
      logo: "/images/newcastlee.png",
      rank: 8,
      name: "NEWCASTLE",
      titles: 2,
    },
    {
      logo: "/images/oporto.png",
      rank: 9,
      name: "PORTO",
      titles: 2,
    },
    {
      logo: "/images/Chelsea.png",
      rank: 10,
      name: "CHELSEA",
      titles: 2,
    },
    {
      logo: "/images/AstonVilla.png",
      rank: 11,
      name: "ASTON VILLA",
      titles: 1,
    },
    {
      logo: "/images/SSC_Neapel.svg.png",
      rank: 12,
      name: "NAPOLI",
      titles: 1,
    },
    {
      logo: "/images/sevillaa.png",
      rank: 13,
      name: "SEVILLA",
      titles: 1,
    },
    {
      logo: "/images/valenciafc.png",
      rank: 14,
      name: "VALENCIA",
      titles: 1,
    },
    {
      logo: "/images/Internazionale.png",
      rank: 15,
      name: "INTER",
      titles: 1,
    },
    {
      logo: "/images/arsenalfc.png",
      rank: 16,
      name: "ARSENAL",
      titles: 1,
    },
    {
      logo: "/images/da-removebg-preview.png",
      rank: 17,
      name: "JUVENTUS",
      titles: 1,
    },
    {
      logo: "/images/villar.png",
      rank: 18,
      name: "VILLA REAL",
      titles: 1,
    },
    {
      logo: "/images/Liverpool.png",
      rank: 19,
      name: "LIVERPOOL",
      titles: 1,
    },
    {
      logo: "/images/Ajax.png",
      rank: 20,
      name: "AJAX",
      titles: 1,
    },
    {
      logo: "/images/Zenit.png",
      rank: 21,
      name: "ZENIT",
      titles: 0,
    },
    {
      logo: "/images/BorussiaDortmund.png",
      rank: 22,
      name: "BORUSSIA DORTMUND",
      titles: 0,
    },
    {
      logo: "/images/Milan.png",
      rank: 23,
      name: "AC MILAN",
      titles: 0,
    },
    {
      logo: "/images/laziofc.png",
      rank: 24,
      name: "LAZIO",
      titles: 0,
    },
    {
      logo: "/images/SportingLisboa.png",
      rank: 25,
      name: "SPORTING LISBOA",
      titles: 0,
    },
    
    {
      logo: "/images/AtleticoMadrid.png",
      rank: 26,
      name: "ATL. MADRID",
      titles: 0,
    },
    {
      logo: "/images/evertonfc.png",
      rank: 27,
      name: "EVERTON",
      titles: 0,
    },
    {
      logo: "/images/ASRoma.png",
      rank: 28,
      name: "AS ROMA",
      titles: 0,
    },
    {
      logo: "/images/Benfica.png",
      rank: 29,
      name: "BENFICA",
      titles: 0,
    },
    {
      logo: "/images/wolfburgo.png",
      rank: 30,
      name: "WOLFSBURGO",
      titles: 0,
    },
    {
      logo: "/images/Lyon.png",
      rank: 31,
      name: "LYON",
      titles: 0,
    },
    

    {
      logo: "/images/galatasaray.png",
      rank: 32,
      name: "GALATASARAY",
      titles: 0,
    },
    {
      logo: "/images/fiorentina.png",
      rank: 33,
      name: "FIORENTINA",
      titles: 0,
    },
    {
      logo: "/images/realsociedad.png",
      rank: 34,
      name: "REAL SOCIEDAD",
      titles: 0,
    },
    {
      logo: "/images/BOCA.png",
      rank: 35,
      name: "BOCA JUNIORS",
      titles: 0,
    },
    {
      logo: "/images/river.png",
      rank: 36,
      name: "RIVER PLATE",
      titles: 0,
    },
    {
      logo: "/images/flam.png",
      rank: 37,
      name: "FLAMENGO",
      titles: 0,
    },
    {
      logo: "/images/slo.png",
      rank: 38,
      name: "SAN LORENZO",
      titles: 0,
    },
  ],
};
